update docfx.yaml

diff --git a/.github/workflows/docfx.yaml b/.github/workflows/docfx.yaml
--- a/.github/workflows/docfx.yaml
+++ b/.github/workflows/docfx.yaml
@@ -23,16 +23,29 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
       # KILL ↓
-      - name: 'BUILD_FAILED is set... ERROR'
+      - name: 'BUILD_FAILED is set... ERROR bool'
+        if: env.BUILD_FAILED == true
+        run: |
+          echo ${{ env.BUILD_FAILED }}
+          echo $BUILD_FAILED
+          echo "::error title=BUILD_FAILED=${{ env.BUILD_FAILED }}::Build failed, will not continue with coverage or unit test reports."
+          exit 1
+      - name: 'BUILD_FAILED is set... ERROR str'
         if: ${{ env.BUILD_FAILED == 'true' }}
         run: |
           echo ${{ env.BUILD_FAILED }}
           echo $BUILD_FAILED
           echo "::error title=BUILD_FAILED=${{ env.BUILD_FAILED }}::Build failed, will not continue with coverage or unit test reports."
           exit 1
+      - name: force error exit
+        run: |
+          echo $BUILD_FAILED
+          echo ${{ env.BUILD_FAILED == false }}
+          echo ${{ env.BUILD_FAILED == true }}
+          echo ${{ env.BUILD_FAILED == 'false' }}
+          echo 
+          exit 1
       #
-      - name: KILL
-        run: exit 1
       #
       - name: Checkout
         uses: actions/checkout@v3
