update docfx.yaml

diff --git a/.github/workflows/docfx.yaml b/.github/workflows/docfx.yaml
--- a/.github/workflows/docfx.yaml
+++ b/.github/workflows/docfx.yaml
@@ -23,9 +23,13 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
       # KILL ↓
-      - name: Test if BUILD_FAILED is set
-        if: ${{ env.BUILD_FAILED }}
-        run: echo "::error title=BUILD_FAILED::Build failed, will not continue with coverage or unit test reports."
+      - name: 'BUILD_FAILED is set... ERROR'
+        if: ${{ env.BUILD_FAILED == 'true' }}
+        run: |
+          echo ${{ env.BUILD_FAILED }}
+          echo $BUILD_FAILED
+          echo "::error title=BUILD_FAILED=${{ env.BUILD_FAILED }}::Build failed, will not continue with coverage or unit test reports."
+          exit 1
       #
       - name: KILL
         run: exit 1
