update test-pack-release.yaml

diff --git a/.github/workflows/test-pack-release.yaml b/.github/workflows/test-pack-release.yaml
--- a/.github/workflows/test-pack-release.yaml
+++ b/.github/workflows/test-pack-release.yaml
@@ -111,7 +111,10 @@ jobs:
       # KILL ↓
       - name: Test if BUILD_FAILED is set
         if: ${{ env.BUILD_FAILED }}
-        run: echo "::error title=BUILD_FAILED::Build failed, will not continue with coverage or unit test reports."
+        run: |
+          echo ${{ env.BUILD_FAILED }}
+          echo "::error title=BUILD_FAILED=${{ env.BUILD_FAILED }}::Build failed, will not continue with coverage or unit test reports."
+          exit 1
       #
       - name: Test
         run: |
